How to build.

To bootstrap your build from a clean yroot you can use yinst to set up the exact state that teh build servers are using

cd yahoo-build
yinst restore -file rhel6_build.state

Once that is installed you can build using sbt directly or you can use the Makefiles


The CI dashboard is at
http://re101.ygrid.corp.gq1.yahoo.com:9999/yhudson/job/spark-adp-commit/
